var t=void 0,w=null;
(function(){function ha(){var a=g.c,c,b,f;if(a&&"[object Array]"===Object.prototype.toString.call(a)&&a.length)for(;c=a.shift();)if(c&&c.action&&T(c.action)&&c.arguments&&"[object Array]"===Object.prototype.toString.call(c.arguments)){f=c.action.split(".");for(b=g;f.length;)if(b=b[f.shift()],!b)return;if("function"==typeof b)try{b.apply(b,c.arguments)}catch(e){}}}function U(a,c,b){a[Da]((ia?"on":"")+c,function(a){a=a||g.event;b(a,a.target||a.srcElement)},D)}function ja(a){var c=0,b;for(b in a)a.hasOwnProperty(b)&&
c++;return c}function V(a){a=(a||"").split("#")[0].split("?")[0];var c=a.length;if(c){a=c+"#"+a.charCodeAt(c-1);for(var b=a.length,f=0,c=0;c<b;c++)f=31*f+a.charCodeAt(c);a=f}else a=-1;return a}function ka(){if(!W(u))return u;var a=s.getElementsByTagName("head")[0],c,b,f,e=a?a.getElementsByTagName("meta"):w;if(e){b=0;for(f=e.length;b<f;b++)if(a=e[b],c=p(a,"name"),c==E||"spm-id"==c){F=p(a,"content");0<=F.indexOf(":")&&(c=F.split(":"),X="i"==c[0]?"i":"u",F=c[1]);(a=p(a,Y))&&(X="i"==a?"i":"u");u=(Ea=
0==F.indexOf("110"))?w:F;break}}u=u||w;if(!u)return u;if(a=(a=s.getElementsByTagName("body"))&&a.length?a[0]:w)if(a=p(a,E))c=u.split("."),u=c[0]+"."+a;return u}function Z(a){var c;try{c=K(a.getAttribute("href",2))}catch(b){}return c||""}function p(a,c){return a&&a.getAttribute?a.getAttribute(c)||"":""}function la(a,c){if(a&&a.removeAttribute)try{a.removeAttribute(c)}catch(b){if(a&&a.setAttribute)try{a.setAttribute(c,"")}catch(f){}}}function B(a){var c=[],b,f;for(b in a)a.hasOwnProperty(b)&&(f=""+
a[b],c.push(b==ma?f:b+"="+encodeURIComponent(f)));return c.join("&")}function Fa(a){var c=[],b,f,e,d=a.length;for(e=0;e<d;e++)b=a[e][0],f=""+a[e][1],c.push(b==ma?f:b+"="+encodeURIComponent(f));return c.join("&")}function na(a){var c={},b;for(b in a)a.hasOwnProperty(b)&&(c[b]=a[b]);return c}function oa(a,c){for(var b in c)c.hasOwnProperty(b)&&(a[b]=c[b])}function pa(a){a=a.split("&");for(var c=0,b=a.length,f,e={};c<b;c++)f=a[c].split("="),e[f[0]]=L(f[1]);return e}function W(a){return"undefined"==typeof a}
function T(a){return"string"==typeof a}function qa(a,c){var b,f="BackCompat"==s.compatMode?s.body:s.documentElement,e=Math.max(f.scrollWidth,f.clientWidth);b=Math.max(f.scrollHeight,f.clientHeight);b=[e,b,f.scrollTop,f.scrollLeft];var f=b[0],e=b[1],d=b[2],k=b[3];b=c.pageX;var g=c.pageY;"number"!=typeof b&&(b=c.clientX+k,g=c.clientY+d);var h=-1,j;a&&a.getBoundingClientRect&&(j=a.getBoundingClientRect(),h=j.left+k,j=j.top+d);d=f>>1;j="number"==typeof j?{A:h-d,B:j,z:a.offsetWidth,w:a.offsetHeight}:{};
j.v=f;j.u=e;j.x=b-d;j.y=g;return j}function ra(){M=M||s.getElementsByTagName("head")[0];return sa||(M?sa=M.getElementsByTagName("meta"):[])}function $(a){return(a=s.cookie.match(RegExp("\\b"+a+"=([^;]+)")))?a[1]:""}function N(a){var c,b;try{return c=[].slice.call(a)}catch(f){c=[];b=a.length;for(var e=0;e<b;e++)c.push(a[e]);return c}}function K(a){return T(a)?a.replace(/^\s+|\s+$/g,""):""}function L(a){var c="";if(a)try{c=decodeURIComponent(a)}catch(b){}return c}function ta(a,c){var b=a.split(";"),
f,e=b.length,d,k;for(f=0;f<e;f++)d=b[f].split("="),(k=K(d[0]))&&(c[k]=L(K(d[1])))}function ua(){if(!aa){var a=g.name||"",c=O?s.referrer||z:z,b={L:H};ba&&(b.o=c);-1==a.indexOf("=")?(b.n=a,g.name=B(b)):(O&&a.match(/&?\bwm_referrer=[^&]+/)&&delete b.o,a=pa(a),oa(a,b),g.name=B(a))}}var g=window,s=document;if(s.getElementsByTagName("body").length){if(!g._tb_beacon_loaded){g._tb_beacon_loaded=1;var ba="https:"==s.location.protocol,aa=parent!==self,I=(ba?"https://img":"http://www")+".atpanel.com/",Ga=I+
"1.gif",Ha=I+"ued.1.1.1",Ia=p(s.getElementById("tb-beacon"),"exparams"),Ja=Math.random(),z=location.href,Ka=location.pathname,O=ba&&0<=z.indexOf("login.taobao.com"),M,sa,A={},va,P={},ca,Q,R,x,u,F,X="u",Ea,da,H,ma="::-plain-::",E="data-spm",Y="data-spm-protocol",wa="/theme/info/info /promo/co_header.php fast_buy.htm /add_collection.htm /taobao_digital_iframe /promo/co_header_taoinfo.php".split(" "),xa=(new Date).getTime(),ya=xa,za=0,ia=!!s.attachEvent,Da=ia?"attachEvent":"addEventListener",D=!1,La=
V(z),G={send:function(a,c){var b=new Image,f="_img_"+Math.random(),e=-1==a.indexOf("?")?"?":"&",d=c?B(c):"";g[f]=b;b.onload=b.onerror=function(){g[f]=w};b.src=e=d?a+e+d:a;b=w;return e},i:function(a,c){var b=na(c);b["_gm:id"]=a;return G.f("ued.1.1.2?type=9",{},b,"%")},f:function(a,c,b,f){f=f||w;if(!("%"!=f&&V(z)!=f)&&!(1<ja(c)))return a=I+a,b=na(b),f=-1==a.indexOf("?")?"?":"&",1==ja(c)&&(a+=f+B(c)),b.p=Math.random(),G.send(a,b)}};g.k||(g.k=G);g.l||(g.l={f:G.i});g.c||(g.c=[]);var ea;x=g.name||"";var r=
pa(x),S=r.wm_referrer,C=r.n;ea=s.referrer||L(S);da=r.refer_pv_id;O||(W(C)?W(S)||(g.name=x.replace(/&?\bwm_referrer=[^&]*/g,"")):g.name=L(C));var fa={d:function(){var a;if(!(a=!aa))a:{a=0;for(var c=wa.length;a<c;a++)if(-1!=Ka.indexOf(wa[a])){a=!0;break a}a=!1}a&&fa.send(Ga);if(aa){var b,c=ra(),f=c.length;for(a=0;a<f;a++)b=c[a],"atp-beacon"==p(b,"name")&&(b=p(b,"content"),ta(b,P));B(P);var e;a=P.a;("1"==a||"2"==a)&&((e=P.r)&&e===V(z).toString())&&fa.send("1"==a?"http://ac.atpanel.com/1.gif":"http://www.atpanel.com/1.gif")}O?
ua():v.a(g,"beforeunload",function(){ua()})},send:function(a){var c=new Image,b="_ta_rndid_"+Math.random(),f,e,d=A.e,k=A.I;f=$("cna");e=$("tracknick");g[b]=c;c.onload=c.onerror=function(){g[b]=w};g.F=c.src=a+"?cache="+Math.floor(9999999*Ja+1)+"&pre="+escape(ea)+"&scr="+screen.width+"x"+screen.height+"&ul_chk="+La+(f?"&acookie_cna="+encodeURIComponent(f):"")+(e?"&tracknick="+encodeURIComponent(e):"")+"&isbetanew=1&"+Ia+(da?"&rpi_bi="+da:"")+(H?"&upi_bi="+H:"")+(d?"&wm_pageid="+d:"")+(k?"&wm_prototypeid="+
k:"")+(Q?"&wm_sid="+Q:"")+(R?"&wm_instanceid="+R:"")+(u?"&spm-cnt="+u:"");c=w}},v={g:{},d:function(){v.b=$(v.g.t||"t");v.Q=g.screen.width;v.N=g.screen.height;v.a(s,"mousedown",function(a,c){if(c){var b=c,f,e,d,k=0,g;a:{g=b;for(var h;g&&"BODY"!=g.tagName;)if(h=p(g,"data-spm"),!h||0!=h.indexOf("110")||3!=(d=h.split(".")).length)g=g.parentNode;else{g=d[2];break a}g=""}h={};d=b;for(var j=[],m,l,q;d;){l=d.tagName;if(d.id){j.unshift(l+"#"+d.id);break}if("BODY"==l||"HTML"==l)break;q=0;for(m=d;m=m.previousSibling;)m.tagName==
l&&q++;j.unshift(l+(q?"["+q+"]":""));d=d.parentNode}for(h.T=j.join(" ");b&&b!=s;){(d=b.tagName)&&"HTML"!=d&&(k=1);if(!e&&("A"==d||"AREA"==d||"IMG"==d||"BUTTON"==d||"INPUT"==d||"TEXTAREA"==d))e=b;if("A"==d||"AREA"==d)f=K(b.getAttribute("href",2))||"";if(d=p(b,"data-widgetid"))h.W=d;if(d=p(b,"data-componentid"))h.s=d;if(!(b=b.parentNode))break}k&&(f&&(h.href=f),f=qa(e,a),oa(h,f),za++,h.q=za,f=(new Date).getTime(),h.R=f-xa,h.S=f-ya,ya=f,h.type=1,g&&(h.H=g),v.send(h))}});v.send({type:0})},a:function(a,
c,b){U(a,c,b)},send:function(a,c,b){function f(){g[d]=w}var e=Math.random(),d="rnd_id_"+e;a.J=H;a.K=e;a.referrer=encodeURIComponent(ea);a.b=v.b||"";a.G=ca||"";a.U=A.e||"";c&&(a.type=4);a.C=encodeURIComponent(va);c=new Image;g[d]=c;c.onload=function(){g[d]=w};c.onerror=f;b=(b||Ha)+"?";a.hasOwnProperty("type")&&(b+="type="+a.type,delete a.type);c.src=b+"&"+B(a);c=w;setTimeout(function(){g[d]&&(g[d].src="");f()},5E3)}};if(!(-1<z.indexOf("atp-ignore=1"))){var Aa=function(){ha();setTimeout(Aa,200)};Aa();
U(g,"beforeunload",ha);r=ra();S=r.length;for(x=0;x<S;x++)C=r[x],"microscope-data"==p(C,"name")&&(C=p(C,"content"),ta(C,A));va=B(A);Q=A.O;R=A.P;x=A.e;ca=R||Q;ka();r="";if(!g.g_aplus_pv_id){for(;6>r.length;)r+="0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ".substr(Math.floor(62*Math.random()),1);g.g_aplus_pv_id=r}H=g.g_aplus_pv_id;fa.d();g.V={send:function(a,c){c=c||{};v.send(a,1,c.url)}};var J=function(a,c,b){if(!b){var f=Z(a),e;if(!(e=p(a,Y))){a:{e=a;for(var d;(e=e.parentNode)&&"BODY"!=
e.tagName;)if(d=p(e,Y)){e=d;break a}e=""}e=e||X}e="i"==e;d=I+"tbspm.1.1?spm=";var g;if(g=f){a:{g="mclick.simba.taobao.com click.simba.taobao.com click.tanx.com click.mz.simba.taobao.com click.tz.simba.taobao.com redirect.simba.taobao.com rdstat.tanx.com stat.simba.taobao.com s.click.taobao.com".split(" ");var n,h=g.length;for(n=0;n<h;n++)if(-1!=f.indexOf(g[n])){g=!0;break a}g=!1}g=!g}if(g&&!(!e&&(0==f.indexOf("#")||0==f.toLowerCase().indexOf("javascript:"))||(f?f.match(/^[^\?]*\balipay\.(?:com|net)\b/i):
D)||(f?f.match(/^[^\?]*\balipay\.(?:com|net)\/.*\?.*\bsign=.*/i):D)))if(e)d+=c+"&url="+encodeURIComponent(z)+"&cache="+Math.random(),Ba==a&&G.send(d);else if(!b){(b=f)&&/&?\bspm=[^&#]*/.test(b)&&(b=b.replace(/&?\bspm=[^&#]*/g,"").replace(/&{2,}/g,"&").replace(/\?&/,"?").replace(/\?$/,""));if(c){var j,m,f="&";-1!=b.indexOf("#")&&(m=b.split("#"),b=m.shift(),m=m.join("#"));e=b.split("?");d=e.length-1;0<d&&(j=e.pop(),b=e.join("?"));j&&(1<d&&-1==j.indexOf("&")&&-1!=j.indexOf("%"))&&(f="%26");b=b+"?spm="+
c+(j?f+j:"")+(m?"#"+m:"")}c=b;var l;if((j=a.innerHTML)&&-1==j.indexOf("<"))l=s.createElement("b"),l.style.display="none",a.appendChild(l);a.href=c;l&&a.removeChild(l)}}},ga=function(a){a=p(a,E);return!a||!a.match(/^d\w+$/)?D:a},r=function(a){if(a&&1==a.nodeType){la(a,"data-spm-max-idx");var c=N(a.getElementsByTagName("a"));a=N(a.getElementsByTagName("area"));var c=c.concat(a),b=c.length;for(a=0;a<b;a++)la(c[a],"data-spm-anchor-id")}};if(!g.j){var Ba,Ca;Ca=ca&&x;U(s,"mousedown",function(a,c){if(!g.j)for(var b;c&&
(b=c.tagName);){if("A"==b||"AREA"==b){b=c;var f=a;Ba=b;var e=p(b,"data-spm-anchor-id"),d=t,d=!!p(b,"data-spm-wangpu-module-id");if(e)J(b,e,d);else{for(var e=b.parentNode,k=d=t,n=e;e&&"HTML"!=e.tagName&&"BODY"!=e.tagName&&e.getAttribute;){if(k=e.getAttribute(E)){d=k;n=e;break}if(!(e=e.parentNode))break}d={m:d,h:n};if(d.m){b=d.h;var h=d=k=e=t,j=d=t,m=t,l=d=m=t,l=f=n=h=e=t;if(p(b,"data-spm-delay"))b.setAttribute("data-spm-delay","");else if(e=b.getAttribute(E)||""){for(var k=b,j=h=l=h=l=t,n=[],q=m=t,
r=t,l=N(k.getElementsByTagName("a")),h=N(k.getElementsByTagName("area")),h=l.concat(h),q=0,r=h.length;q<r;q++){m=!1;for(j=l=h[q];(j=j.parentNode)&&j!=k;)if(p(j,E)){m=!0;break}m||n.push(l)}k=n;if(n=Ca&&0==e.indexOf("110"))h=e.split("."),f=h[h.length-1];if(T(d=ka())&&d.match(/^[\w\-\*]+(\.[\w\-\*]+)?$/))if(0<=e.indexOf(".")){if(0!=e.indexOf(d)){d=d.split(".");h=e.split(".");e=0;for(l=d.length;e<l;e++)h[e]=d[e];e=h.join(".")}}else 0<=d.indexOf(".")||(d+=".0"),e=d+"."+e;if(e.match&&e.match(/^[\w\-\*]+\.[\w\-\*]+\.[\w\-\*]+$/)){l=
parseInt(p(b,"data-spm-max-idx"))||0;h=0;j=l;for(l=k.length;h<l;h++)if(d=k[h],m=Z(d))n&&d.setAttribute("data-spm-wangpu-module-id",f),(m=d.getAttribute("data-spm-anchor-id"))?J(d,m,n):(j++,m=e+(n?"":"."+(ga(d)||j)),J(d,m,n),d.setAttribute("data-spm-anchor-id",m));b.setAttribute("data-spm-max-idx",j)}}}else a:{j=f;f=Z(b);d=t;d=(e=f&&(d=f.match(/&?\bspm=([^&#]*)/))?d[1]:"")?e.split("."):w;n=k=t;n=u&&2==(k=u.split(".")).length;if(!n&&1E-4>Math.random()){for(var h=b,l=f,m=j,j=(new Date).getTime(),q=t,
q=h,r=[],v=t,y=t;q&&1==q.nodeType;q=q.parentNode){for(var v=1,y=t,x=q.tagName,y=q.previousSibling;y;y=y.previousSibling)1==y.nodeType&&y.tagName==x&&v++;y=q.tagName;1<v&&(y+="["+v+"]");r.unshift(y)}q="/"+r.join("/");h=qa(h,m);G.send(I+"tbtestspm.1.1?"+Fa([["url",l],["x",h.x],["y",h.y],["time",(new Date).getTime()-j],["xpath",q],["cache",Math.random()]]))}if(d&&4<=d.length){if("1003"==d[0]||"2006"==d[0])break a;if(n){d[0]=k[0];d[1]=k[1];(n=ga(b))&&(d[3]=n);J(b,d.slice(0,4).join("."),D);break a}}else if(n){f=
u;if(!(e=ga(b)))b:{e=s.getElementsByTagName("a");d=e.length;k=t;for(k=0;k<d;k++)if(e[k]==b){e=k+1;break b}e=0}d=[f,0,e];J(b,d.join("."),D);break a}f&&e&&(b.href=" "+f.replace(/&?\bspm=[^&#]*/g,"").replace(/&{2,}/g,"&").replace(/\?&/,"?").replace(/\?$/,"").replace(/\?#/,"#"))}}break}else if("BODY"==b||"HTML"==b)break;c=c.parentNode}});g.D={M:r}}}}}else setTimeout(arguments.callee,50)})();
